version: '3.3'
services:
  mongo:
    container_name: mongo
    image: mongo:4.2.2
    environment:
      MONGO_INITDB_DATABASE: mobilebe
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - data:/data/db
    restart: always