version: '3.7'
services:
  mongodb_container:
    image: mongo:4.2.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: mydb
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data: